#! /bin/sh

bspc config border_width	2
bspc config window_gap		8

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 1
bspc config focus_follows_pointer true

bspc monitor -d web term chat code music

bspc config normal_border_color '#282828'
bspc config focused_border_color '#c3c3c3'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#1d2021'
bspc config focused_sticky_border_color '#d5c4a1'
bspc config urgent_border_color '#cc241d'

bspc rule -a firefox border=off
bspc rule -a URxvt state=tiling
bspc rule -a mpv state=floating


~/.config/polybar/launch.sh
